### ISSUE TITLE
Publish to store

### ISSUE THREAD

**Issue by abhijithvijayan** [rabeehrz/better-ktu#2]
Why not publish it to store?

**Comment by rabeehrz** [comment]
@abhijithvijayan I tried. I got declined. I don't remember the exact wordings (I was half asleep), but what they said was that since the KTU Portal was not accessible to the public, they cannot put the addon on the store. They told it would be better for me to sign it myself and self distribute it. 😅

**Comment by abhijithvijayan** [comment]
Maybe try again with new description.

Firefox has less chance of rejection than chrome.

**Comment by rabeehrz** [comment]
I didn't try the chrome store, as Google Chrome doesn't support addons on Android (AFAIK). The one I tried was Mozilla. I will read about it a bit more and try again later.

**Comment by abhijithvijayan** [comment]
I know.

Chrome/Edge doesnt seem to support extensions yet.

Kiwi(chromium based fork) supports it. 

Even if the chrome supported it, Google Store would just decline for just about any tiny reason.
